#!/bin/bash 
#
#  wi - a lightweight network utility for *nix
#  Copyright (C) 2012 Blake Bartenbach
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#-----------
# Variables
#-----------
version='0.0.6-indev'
wi_home="/etc/wi"
wi_conf="$wi_home/wi.conf"
iface=''
essid=''
enc=''
color=''
green='\e[0;32m'
red='\e[0;31m'
yellow='\e[0;93m'

#------------
# Exit codes
#------------
not_root='10' # User needed to be root and was not
interface_not_found='15' # The interface supplied does not exist
no_arguments='20' # No arguments were supplied
missing_arguments='25' # An argument is missing
no_connection='30' # We exited without obtaining a connection
no_enc='35' # Encryption key was not supplied and is required
cannot_set_interface_down='40' # Shell returned non-zero on set down attempt
cannot_associate_with_essid='50' # Problem associating with the ESSID
cannot_set_interface_up='60' # Shell returned non-zero on set up attempt
cannot_start_dhcpcd='65' # Shell returned non-zero starting dhcpcd
network_not_found='70' # Failed to find ESSID via iwlist scan
cannot_set_wep_key='90' # Unable to set wep key
iwlist_scan_failed='100' # scanning with iwlist failed

#-----------
# Functions
#-----------
function ensure_root {
  if [[ $EUID != 0 ]];then
    echo "You must be root to manage network interfaces" && exit $not_root
  fi
}

function echo_usage {
  echo "Usage: wi [arguments]" 
  echo "  -o, --open interface essid      Connect to an open or unsecured wireless"
  echo "                                  network via dhcp"
  echo "  -e, --wep interface essid pass  Connect to a WEP secured network using the"
  echo "                                  password 'pass'"
  echo "  -a, --wpa interface essid pass  Connect to a WPA secured network using the"
  echo "                                  password 'pass' "
  echo "  -w, --wired interface           Connect to a wired network using interface"
  echo "                                  via dhcp "
  echo "  -t, --test                      Check for a current internet connection"
  echo "  -s, --scan interface            Scan for wireless networks with interface"
  echo "  -h, --help                      Show this menu"
  echo "  --version                       Print the current version of wi"
}

#-----------------
# Parse arguments
#-----------------
parse_arguments_case() {
  while :
    do
      case $1 in
      
      esac
    done  
}

parse_arguments() {
  if [[ $1 == '--version' ]];then
    echo "v$version" && exit 0
  elif [[ $1 == '-h' ]] || [[ $1 == '--help' ]];then
    echo_usage && exit 0
  elif [[ $1 == '-s' ]] || [[ $1 == '--scan' ]];then
    [[ -z $2 ]] && exit_noargs $1
    scan $* && exit 0
  elif [[ $1 == '-t' ]] || [[ $1 == '--test' ]];then
    test_connection && exit 0
  elif [[ $1 == '-o' ]] || [[ $1 == '--open' ]];then
    [[ -z $2 ]] || [[ -z $3 ]] && exit_noargs $1
    connect_unsecured_wireless_dhcp $* && exit 0
  elif [[ $1 == '-e' ]] || [[ $1 == '--wep' ]];then
    [[ -z $2 ]] || [[ -z $3 ]] || [[ -z $4 ]] && exit_noargs $1
    connect_wireless_WEP_dhcp $* && exit 0 
  elif [[ $1 == '-a' ]] || [[ $1 == '--wpa' ]];then
    [[ -z $2 ]] || [[ -z $3 ]] && exit_noargs $1
    connect_wireless_wpa_dhcp $* && exit 0 
  elif [[ $1 == '-w' ]] || [[ $1 == '--wired' ]];then
    [[ -z $2 ]] && exit_noargs $1
    connect_wired_dhcp $* && exit 0
  else
    echo_usage && exit $no_arguments
  fi  
}

exit_noargs() {
  echo "Missing argument for $1 (See wi -h,--help)" && exit $missing_arguments
}

assign_arguments() {
  iface=$2
  essid=$3
  enc=$4
}

#---------------------
# Interface functions
#---------------------
function set_interface_down {
  ip l s $iface down &>/dev/null && check_exit $cannot_set_interface_down
}

function set_interface_up {
  ip l s $iface up &>/dev/null && check_exit $cannot_set_interface_up
}

function associate_with_essid {
  iwconfig $iface essid $essid &>/dev/null && check_exit $cannot_associate_with_essid
}

function start_dhcpcd {
  dhcpcd -K -A $iface &>/dev/null && check_exit $cannot_start_dhcpcd
}

function kill_dhcpcd {
  pkill -9 dhcpcd &>/dev/null && rm /run/dhcpcd-$iface.pid &>/dev/null
}

function isUp {
  `ip link show up | grep $iface &>/dev/null`
  if [[ $? != 0 ]];then
    set_interface_up
    sleep 1
  fi
}

function ping_check {
  ping -c1 -W1 google.com &>/dev/null
}

#------
# Test
#------
function test_connection {
  ping_check
  if [[ $? == 0 ]];then
    echo "[Connected]"
  else
    echo "[No connection]"
  fi
}

#----------
# Scan
#----------
scan() {
  assign_arguments $*
  ensure_root && check_exit $not_root
  isUp
  echo "[Scanning for networks with $iface]"
  iwlist $iface scan | grep ESSID | tr -d [:blank:] | tr -d [\"] #TODO this is totally fucked up
  # this needs to iterate through them one by one and avoid printing empty strings
  # it needs to print out encryption details, and probably some other important data.
  # it should also print nothing if the scan has failed
  check_scan
}

function check_scan {
  if [[ $? == 0 ]];then
    echo "[Scan complete]" && exit 0
  fi
  echo "[Scan failed]" && exit $iwlist_scan_failed 
}

#--------------------
# Configuration file
#--------------------
function check_config {
  if [[ -f $wi_conf ]]; then
    . $wi_conf && return
  fi 
  echo "[Created new configuration file at $wi_conf]"
  mkdir -p $wi_home && touch $wi_conf
  write_default_config
}

function write_default_config {
  write "# wi configuration file"
  write ""
  write "# use color? true/false"
  write "color=false"
}

write() {
  echo $1 >> $wi_conf  
}

#------------------
# Validation
#------------------
function validate_essid {
  isUp
  for scanned_essid in `iwlist $iface scan | grep ESSID | tr -d [:blank:] | tr -d [\"]`
    do
      [[ "ESSID:$essid" == "$scanned_essid" ]] && return
    done
  echo -e "$red[Network \"${yellow}$essid${red}\" not found]$reset"
  exit $network_not_found
}

function validate_interface {
  ip link show dev $iface &>/dev/null
  [[ $? -eq 0 ]] && return
  echo -e "$red[Network interface \"${yellow}$iface$red\" not detected]$reset"
  exit $interface_not_found
}
#--------
# Checks
#--------
function check_connection {
  ping_check
  if [[ $? == 0 ]];then
    echo -e "$green[Connected to $essid]$reset" && exit 0
  else
    return $no_connection
  fi
}

check_exit() {
  if [[ $? != 0 ]];then
    echo "[Error] exit: $1" && exit $1
  fi
}

#--------------------
# Retry to get an IP //TODO Needs to be tested more
#--------------------
function dhcp_persist {
  let j=1
  while (( j < 5 )) && (( $? > 0 ))
    do
    echo "[Failed to lease an IP]"
    echo "[Retrying ($j/5)]"
    retry_wireless_dhcp
    ((j+=1))
   done 
}

#------------------------------
# Generic connection functions
#------------------------------
function pre_connect {
  ensure_root && check_config
}

function reset_environment {
  set_interface_down && check_exit $cannot_set_interface_down 
  kill_dhcpcd
}

function associate {
  associate_with_essid && check_exit $cannot_associate_with_essid 
}

function put_interface_up {
  isUp && check_exit $cannot_set_interface_up  
}

function retry_if_needed {
  [[ $? -ne "0" ]] && dhcp_persist    
}

function generic_wireless {
  pre_connect
  validate_interface
  echo "[Scanning]" && validate_essid
  echo "[Resetting environment]" && reset_environment
  sleep 1
  echo "[Associating with $essid]" && associate
  sleep 1
}

#--------------------------
# Wireless dhcp connection
#--------------------------
connect_unsecured_wireless_dhcp() {
  assign_arguments $*
  generic_wireless
  echo "[Putting $iface up]" && put_interface_up
  sleep 1
  echo "[Starting dhcp]" && start_dhcpcd
  check_connection && retry_if_needed
}

function retry_wireless_dhcp {
  validate_essid
  reset_environment
  sleep 1
  associate
  sleep 1
  put_interface_up
  sleep 1
  start_dhcpcd
  check_connection
}

#-------------------------
# Wireless WEP connection
#-------------------------
connect_wireless_WEP_dhcp() {
  assign_arguments $* 
  generic_wireless
  echo "[Setting WEP encyption]" && set_wep_encryption
  sleep 1
  echo "[Putting $iface up]" && put_interface_up
  sleep 1
  echo "$green[Acquiring an IP address]$reset" && start_dhcpcd
  test_connection
}

function set_wep_encryption {
  iwconfig $iface key $enc >/dev/null 2>&1 && check_exit $cannot_set_wep_key
}

#-------------------------
# Wireless WPA connection
#-------------------------
connect_wireless_wpa_dhcp() {
  assign_arguments $*
  generic_wireless
  set_wpa_key
  start_wpa_supplicant
  sleep 1
  put_interface_up
  sleep 1
  echo -e "$green[Acquiring an IP address]$reset"
  start_dhcpcd
  check_connection
  retry_if_needed
}

set_wpa_key() {
  cat /etc/wpa_supplicant.conf | grep $essid &>/dev/null
  if [[ $? != 0 ]];then
    if [[ -z $enc ]];then
      echo -e "$yellow[Encryption key for $essid not found]$reset"
      echo -e "$yellow[Please enter the encryption key for $essid]$reset"
      wpa_passphrase $essid >> /etc/wpa_supplicant.conf
    elif [[ -n $enc ]];then
      wpa_passphrase $essid $enc >> /etc/wpa_supplicant.conf
    fi
  fi
}

start_wpa_supplicant() {
  wpa_supplicant -B -c/etc/wpa_supplicant.conf -i$iface
}

#------------------------
# Wired dhcp connecction
#------------------------
connect_wired_dhcp() {
  assign_arguments $*
  pre_connect
  validate_interface
  echo "[Resetting environment]" && reset_environment
  sleep 1
  echo "[Putting $iface up]" && put_interface_up
  sleep 1
  echo "[Acquiring an IP address]" && start_dhcpcd
  sleep 1
  test_connection
}

#---------------------
#//TODO Progress bar?
#---------------------

#---------------------------------
#//TODO Connectivity testing loop
#---------------------------------

#--------------------------------
#//TODO Verify interface exists
#--------------------------------

#-----
# Run
#-----
#set -x
parse_arguments $*
